### ISSUE TITLE
Merge with AoKMiKeY's GUI update

### ISSUE THREAD

**Issue by AoKMiKeY** [mcd1992/fgt_xray#3]
Hay ya, I have been using this mod since 1.6. Love how it renders the blocks so i though i would pick it up. I actually got hold of the source back in 1.6 and updated it myself but once i had seen what you had added i decided to move to your new one. Once 1.7.10 was brought out and this mod did not want to work i just updated it myself :). Not been working with forge for that long but i know my way around java. :). 

So yeah. I can maintain and add to this mod if you would like me to take over development. Not sure if github has a messaging system so yeah.

I have an email if you would like to talk more:
aokmikey@gmail.com
skype: mike12074

**Comment by mcd1992** [comment]
The current code in the master branch works just fine for me on MC 1.7.10 with forge. Although any fixes or additions you have made I'd be more than willing to merge through a pull request. So please feel free to fork this repo and make your changes, then submit a pull request and I'll review it.

Thanks for helping!

**Comment by AoKMiKeY** [comment]
Okay, Cool. I will be sure to get one set up with in the current week. I am currently working on finishing off the adding ore thing. Once that is done i will get it submitted :). Going to be working on a nicer (ish) UI for the adding and toggling of ores.
